-- 007_drop_unused_feedback_tables.sql (Spec-007 T201-T204)
--
-- Retires the two legacy feedback tables that 000_initial_schema.sql
-- carried for fresh-DB <-> old-prod-DB parity but that production has
-- never written to.
--
-- Background (see 000_initial_schema.sql lines 138-156): the production
-- feedback path landed in migration 002 (``user_feedback``). The legacy
-- ``feedback_records`` (parent) + ``feedback_analyses`` (child, FK
-- -> feedback_records.id) pair was kept in 000 only to preserve schema
-- parity with pre-002 databases. No service / chain / endpoint reads or
-- writes either legacy table:
--
--   * ``app/services/feedback.py`` SQL targets ``user_feedback`` only
--     (line 114, 185, 218); the bare identifier ``feedback_records``
--     appears at line 310 solely as a Python parameter name on
--     ``adjust_weights(feedback_records: list[dict])`` — not a SQL
--     reference, so the runner's table-coverage check (regex on
--     FROM/INTO/UPDATE/JOIN) never required a migration for it.
--   * The LLM prompt at ``app/prompts/creator_profile/v1/system.md``
--     mentions the legacy table by name for historical context only.
--   * No migration, service, chain, router, or test inserts into either
--     legacy table on the production code path.
--
-- DROP order: child (feedback_analyses) first, then parent
-- (feedback_records). The runner's connection already has
-- ``PRAGMA foreign_keys=ON`` set (runner.py:208), so the FK constraint
-- is enforced and the child-must-go-first ordering is required to
-- avoid an ``FOREIGN KEY constraint failed`` error on the parent drop.
--
-- ``IF NOT EXISTS`` semantics for DROP aren't a thing in SQLite, but
-- ``DROP TABLE IF EXISTS`` IS supported (it is a no-op when the table
-- is absent), which keeps this migration safe to re-run if the runner's
-- checksum state ever drifts. Combined with the runner's
-- schema_migrations version check, the file is normally applied
-- exactly once.

DROP TABLE IF EXISTS feedback_analyses;
DROP TABLE IF EXISTS feedback_records;
